### Edit the Project Id and the API Key in the .vscode/settings.json file
@BaseRequestUrl = https://api.{{BaseUrl}}/v1/projects/{{ProjectId}}

### Start Deployment
# Use the new deployment Id created in Post-Create-Deployment 
@FreshDeploymentId = 

PATCH {{BaseRequestUrl}}/deployments/{{FreshDeploymentId}} HTTP/1.1
Umbraco-Cloud-Api-Key: {{ApiKey}}
Content-Type: application/json
{
    "deploymentState": "Queued"
} 

