name: Prepare and Upload Artifact

on:
  workflow_call:
    inputs:
      newSha:
        required: false
        type: string
    secrets:
      projectId:
        required: true
      umbracoCloudApiKey:
        required: true
    outputs:
      artifactId:
        description: 'The Id of the uploaded artifact'
        value: ${{ jobs.prepareDeployment.outputs.artifactId }}

jobs:
  prepareDeployment:
    name: Prepare Artifact to cloud
    runs-on: ubuntu-latest
    outputs:
      artifactId: ${{ steps.upload-artifact.outputs.artifactId }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.newSha }}

      # switch the gitignore files so cloud does not ignore the build frontend assets
      # zip everything, except what is defined in the 'cloud.zipignore'
      - name: Prepare Cloud Git Ignore and Zip Source Code
        run: |
          echo "switching .gitignore with cloud.gitignore"
          cp cloud.gitignore .gitignore
          echo "Packing artifact for upload"
          zip -r sources.zip . -x@cloud.zipignore
        shell: bash

      # Upload your zipped artifact
      - name: Post Zipped Artifact
        id: upload-artifact
        shell: bash
        run: >
          bash ${{ GITHUB.WORKSPACE }}/.github/scripts/upload_artifact.sh 
          ${{ secrets.projectId }} 
          ${{ secrets.umbracoCloudApiKey }} 
          "${{ GITHUB.WORKSPACE }}/sources.zip" 
          "Artifact for ${{ github.run_number }}" 
          "${{ github.run_number }}" 
          GITHUB