name: pipeline # You can add your own name for the pipeline here

# Trigger when committing to main branch
on:
  push:
    branches:
      - main
      - flexible
  workflow_dispatch: # Allow manual triggering of the workflow

jobs:
  # resolve which environment to deploy to based on triggering branch
  set-env:
    runs-on: ubuntu-latest
    outputs:
      targetEnvironmentAlias: ${{ steps.set.outputs.targetEnvironmentAlias }}
    steps:
      - name: Resolve Target Environment
        id: set
        run: |
          echo "Triggering branch: ${{ github.ref_name }}"
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "Target is: $leftmostMainline"
            echo "targetEnvironmentAlias=$leftmostMainline" >> $GITHUB_OUTPUT
          elif [ "${{ github.ref_name }}" = "flexible" ]; then
            echo "Target is: $flexible"
            echo "targetEnvironmentAlias=$flexible" >> $GITHUB_OUTPUT
          else
            echo "no target environment defined for branch: $(Build.SourceBranchName)"
            exit 1
          fi
        env:
          leftmostMainline: ${{ vars.TARGET_ENVIRONMENT_ALIAS}}
          flexible: ${{ vars.FLEXIBLE_ENVIRONMENT_ALIAS }}

  # Get changes from cloud
  cloud-sync:
    needs: set-env
    name: "Umbraco Cloud Sync"
    uses: ./.github/workflows/cloud-sync.yml
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
    with:
      targetEnvironmentAlias: ${{ needs.set-env.outputs.targetEnvironmentAlias }}

  # Pack and upload the deployment Artifact
  cloud-artifact:
    name: "Prepare and Upload Artifact"
    uses: ./.github/workflows/cloud-artifact.yml
    needs: cloud-sync
    with:
      newSha: ${{ needs.cloud-sync.outputs.newSha }}
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  # Deploy to Umbraco Cloud
  # ####
  # you can edit the variables noBuildAndRestore, skipVersionCheck, skipPreserveUmbracoCloudJson,
  # allowAnyTarget and runSchemaExtraction
  # use 0 for false and 1 for true
  cloud-deployment:
    name: "Deploy to Cloud"
    needs: [set-env, cloud-artifact]
    uses: ./.github/workflows/cloud-deployment.yml
    with:
      artifactId: ${{ needs.cloud-artifact.outputs.artifactId }}
      targetEnvironmentAlias: ${{ needs.set-env.outputs.targetEnvironmentAlias }}
      noBuildAndRestore: 0
      skipVersionCheck: 0
      skipPreserveUmbracoCloudJson: 0
      allowAnyTarget: 0
      runSchemaExtraction: 1
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}