name: pipeline

# Trigger when committing to main branch
on:
  push:
    branches:
      - main

jobs:
  # Try to sync the local repository to get up to speed with any changes in Cloud project
  cloud-sync:
    uses: ./.github/workflows/cloud-sync.yml
    secrets:
      projectId: ${{ secrets.PROJECT_ID }}
      umbracoCloudApiKey: ${{ secrets.UMBRACO_CLOUD_API_KEY }}

  # Package and Deploy to Umbraco Cloud
  cloud-deployment:
    needs: cloud-sync
    uses: ./.github/workflows/cloud-deployment.yml
    with:
      newSha: ${{ needs.cloud-sync.outputs.newSha }}
    secrets:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      UMBRACO_CLOUD_API_KEY: ${{ secrets.UMBRACO_CLOUD_API_KEY }}
